name: "Expand Team Reviewers"
description: "Expands team reviewers into list of individual reviewers"
inputs:
  token:
    description: "Token used to access the GitHub API"
    required: true
  label-used-to-trigger:
    description: "Name of the pull request label that was used to trigger this action so it can be removed after execution"
    required: false
    default: "expand team reviewers"
runs:
  using: "node12"
  main: "dist/index.js"
